"use client";

import { motion } from "framer-motion";

type Section = {
  id: string;
  title: string;
  body: ReadonlyArray<string | { type: "list"; items: ReadonlyArray<string> }>;
};

const SECTIONS: ReadonlyArray<Section> = [
  {
    id: "acceptance",
    title: "1. Acceptance of terms",
    body: [
      "By accessing or using ManyMinds, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access our AI council platform.",
      "These terms apply to all visitors, users, and others who access the service — including any Council members you configure.",
    ],
  },
  {
    id: "acceptable-use",
    title: "2. Acceptable use",
    body: [
      "Spirited debate is a core feature of the platform — but targeted harassment, illegal content generation, or attempts to produce malicious software architectures will result in immediate account termination.",
      { type: "list", items: [
        "Don&apos;t use the council to generate illegal, harmful, or explicitly abusive content.",
        "Don&apos;t impersonate other people or organisations.",
        "Don&apos;t attempt to extract our underlying personality system prompts.",
        "Don&apos;t use the platform to facilitate spam or fraud.",
      ]},
    ],
  },
  {
    id: "ip",
    title: "3. Intellectual property",
    body: [
      "You retain all ownership rights to the original prompts, concepts, and ideas you input into the system. The Council personalities (Aria, Rex, Sage, Nova, Echo) and their underlying psychological architectures remain the intellectual property of ManyMinds.",
      "You may export your memory graph as JSON at any time. The data is yours — the system that interprets it is ours.",
    ],
  },
  {
    id: "availability",
    title: "4. Service availability",
    body: [
      "We target 99.9% uptime for Pioneer and Visionary tiers. The nature of large-model orchestration means temporary latency spikes or degraded performance during peak compute hours may occur.",
      "Explorer (free) tier users may experience throttling during high-demand windows.",
    ],
  },
  {
    id: "liability",
    title: "5. Limitation of liability",
    body: [
      "ManyMinds is provided &ldquo;as is&rdquo;. We are not liable for any business decisions, financial losses, or strategic errors made based on the consensus generated by your Council. The council is a thinking partner, not a fiduciary.",
    ],
  },
];

export default function TermsPage() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
      className="relative grid lg:grid-cols-[1fr_220px] gap-12"
    >
      <article>
        <header className="mb-12">
          <p className="text-[11px] font-[var(--font-label)] uppercase tracking-[0.32em] text-white/55 mb-4">
            Effective · March 2026
          </p>
          <h1 className="font-[var(--font-headline)] text-4xl md:text-5xl font-bold leading-[1.05] tracking-tight mb-4">
            <span className="text-white">Terms of</span>{" "}
            <span className="aurora-text">Service</span>
          </h1>
          <p className="text-white/65 text-base leading-relaxed max-w-prose">
            The plain-English rules of being on ManyMinds. Read them once,
            they&apos;ll show up again only if we change something material.
          </p>
          <div
            aria-hidden
            className="mt-8 h-px"
            style={{
              background:
                "linear-gradient(90deg, transparent, rgba(216,163,184,0.4), rgba(212,154,122,0.4), transparent)",
            }}
          />
        </header>

        <div className="space-y-12 text-white/75 leading-relaxed">
          {SECTIONS.map((s) => (
            <section key={s.id} id={s.id} className="scroll-mt-28">
              <h2 className="font-[var(--font-headline)] text-2xl font-bold text-white mb-4">
                {s.title}
              </h2>
              <div className="space-y-4">
                {s.body.map((b, i) =>
                  typeof b === "string" ? (
                    <p key={i}>{b}</p>
                  ) : (
                    <ul
                      key={i}
                      className="list-disc list-outside pl-5 space-y-2 text-white/65"
                    >
                      {b.items.map((it) => (
                        <li
                          key={it}
                          dangerouslySetInnerHTML={{ __html: it }}
                        />
                      ))}
                    </ul>
                  )
                )}
              </div>
            </section>
          ))}
        </div>
      </article>

      <aside className="hidden lg:block">
        <div className="sticky top-28">
          <p className="text-[11px] font-[var(--font-label)] uppercase tracking-[0.22em] text-white/55 mb-3">
            On this page
          </p>
          <ul className="space-y-2 text-sm border-l border-white/10 pl-4">
            {SECTIONS.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-white/55 hover:text-white transition-colors block py-0.5 hover:underline hover:underline-offset-4 decoration-[color:var(--color-nova)] hover:decoration-2"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </div>
      </aside>
    </motion.div>
  );
}
